size_per_page: 5
user:
  username:
    maximum: 20
  email:
    maximum: 50
  role:
    admin: "admin"
    member: "member"
position:
  abbreviation:
    maximum: 255
project:
  abbreviation:
    maximum: 255
zero: "0"
admin: admin
one: "1"
level:
  none: "none"
  pro: "pro"
  beginner: "bengin"
  top: "top"
log:
  twoday: 2
